import React from 'react';
import { motion } from 'framer-motion';
import { Thermometer, Droplets, Activity, Cpu } from 'lucide-react';
import { useEnvironment } from '../hooks/useEnvironment';
import { 
  ENVIRONMENT_CONFIG, 
  getTemperatureStatus, 
  getHumidityStatus 
} from '../config/environmentConfig';

export function EnvironmentalSection({ className = '' }) {
  const envData = useEnvironment();
  const { temperature, humidity, source, timestamp } = envData;

  const tempStatus = getTemperatureStatus(temperature);
  const humStatus = getHumidityStatus(humidity);

  const isSimulated = source === 'simulation';

  // Calculate percentage within the visual indicator range scales
  const tempScale = ENVIRONMENT_CONFIG.SCALES.TEMPERATURE;
  const humScale = ENVIRONMENT_CONFIG.SCALES.HUMIDITY;

  const tempPercent = Math.min(
    100,
    Math.max(0, ((temperature - tempScale.MIN) / (tempScale.MAX - tempScale.MIN)) * 100)
  );

  const humPercent = Math.min(
    100,
    Math.max(0, ((humidity - humScale.MIN) / (humScale.MAX - humScale.MIN)) * 100)
  );

  return (
    <section className={`space-y-3.5 sm:space-y-4 ${className}`} aria-label="Environmental Monitoring">
      {/* Section Header */}
      <div className="flex flex-wrap items-center justify-between gap-2.5 pb-1">
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 sm:p-2 rounded-[10px] bg-[#F1F5F9] border border-[#E2E8F0] text-[#475569] shadow-xs">
            <Activity className="w-4 h-4 text-[#2563EB]" />
          </div>
          <div>
            <h3 className="text-sm sm:text-base font-extrabold text-[#0F172A] tracking-tight flex items-center gap-2">
              Environmental Monitoring
            </h3>
            <p className="text-[11px] sm:text-xs text-[#64748B] font-semibold">
              Facility ambient climate & ventilation telemetry
            </p>
          </div>
        </div>

        {/* Source Badge (Simulated Data vs DHT Hardware) */}
        <div className="flex items-center gap-2">
          {isSimulated ? (
            <div 
              title="Values are currently generated by the software simulation engine. DHT11/DHT22 hardware integration ready."
              className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold border border-[#E2E8F0] bg-white text-[#475569] shadow-xs"
            >
              <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
              <span>Simulated Data</span>
            </div>
          ) : (
            <div 
              title="Receiving live telemetry from DHT physical sensor on ESP32."
              className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold border border-[#A7F3D0] bg-[#ECFDF5] text-[#059669] shadow-xs"
            >
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <Cpu className="w-3 h-3 text-[#059669]" />
              <span>Live DHT Sensor</span>
            </div>
          )}
        </div>
      </div>

      {/* Metric Cards Grid (Desktop side-by-side, responsive stacking on mobile) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 sm:gap-5">
        {/* 1. Temperature Card */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          whileHover={{ y: -4, boxShadow: '0 12px 28px -6px rgba(15,23,42,0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-white rounded-[14px] sm:rounded-[16px] p-4 sm:p-5 border border-[#E2E8F0] shadow-card hover:border-[#3B82F6]/50 transition-all flex flex-col justify-between group"
        >
          {/* Card Top: Icon, Label, and Intelligent Status Pill */}
          <div className="flex items-start justify-between gap-2 mb-3">
            <div className="flex items-center gap-3">
              <div className="p-2 sm:p-2.5 rounded-[10px] bg-[#FFF7ED] text-[#EA580C] border border-[#FFEDD5] shrink-0 group-hover:scale-105 transition-transform">
                <Thermometer className="w-4 h-4 sm:w-5 sm:h-5" />
              </div>
              <div>
                <span className="text-xs sm:text-[13px] font-bold text-[#0F172A] block leading-tight">
                  Indoor Environment
                </span>
                <span className="text-[10px] sm:text-[11px] font-medium text-[#64748B]">
                  Ambient Bay Temperature
                </span>
              </div>
            </div>

            {/* Status Pill */}
            <span className={`text-[11px] font-extrabold px-2.5 py-0.5 rounded-full border shadow-2xs shrink-0 ${tempStatus.badgeClass}`}>
              {tempStatus.status}
            </span>
          </div>

          {/* Card Middle: Primary Numerical Value Display */}
          <div className="my-2 flex items-baseline justify-between">
            <div className="flex items-baseline">
              <motion.span
                key={temperature}
                initial={{ opacity: 0.7, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.25 }}
                className="text-3xl sm:text-4xl font-black text-[#0F172A] tracking-tight leading-none"
              >
                {temperature.toFixed(1)}
              </motion.span>
              <span className="text-lg sm:text-xl font-bold text-[#64748B] ml-1.5">
                °C
              </span>
            </div>

            <span className="text-[11px] text-[#64748B] font-medium hidden xs:inline-block">
              Scale: 10°C – 42°C
            </span>
          </div>

          {/* Card Bottom: Visual Range Indicator Bar */}
          <div className="mt-3 pt-3 border-t border-[#F1F5F9] space-y-1.5">
            <div className="w-full h-2 bg-[#F1F5F9] rounded-full overflow-hidden border border-[#E2E8F0]/70 p-0.5 flex items-center">
              <motion.div
                className="h-full rounded-full transition-all duration-700 ease-out"
                style={{ 
                  backgroundColor: tempStatus.indicatorColor,
                  width: `${tempPercent}%` 
                }}
                initial={{ width: 0 }}
                animate={{ width: `${tempPercent}%` }}
              />
            </div>

            <div className="flex items-center justify-between text-[10px] font-semibold text-[#94A3B8]">
              <span>10°C</span>
              <span className="text-[#64748B]">Normal ({tempScale.NORMAL_RANGE})</span>
              <span>42°C</span>
            </div>
          </div>
        </motion.div>

        {/* 2. Humidity Card */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          whileHover={{ y: -4, boxShadow: '0 12px 28px -6px rgba(15,23,42,0.08)' }}
          transition={{ type: 'spring', stiffness: 400, damping: 25 }}
          className="bg-white rounded-[14px] sm:rounded-[16px] p-4 sm:p-5 border border-[#E2E8F0] shadow-card hover:border-[#3B82F6]/50 transition-all flex flex-col justify-between group"
        >
          {/* Card Top: Icon, Label, and Intelligent Status Pill */}
          <div className="flex items-start justify-between gap-2 mb-3">
            <div className="flex items-center gap-3">
              <div className="p-2 sm:p-2.5 rounded-[10px] bg-[#EFF6FF] text-[#2563EB] border border-[#BFDBFE] shrink-0 group-hover:scale-105 transition-transform">
                <Droplets className="w-4 h-4 sm:w-5 sm:h-5" />
              </div>
              <div>
                <span className="text-xs sm:text-[13px] font-bold text-[#0F172A] block leading-tight">
                  Relative Humidity
                </span>
                <span className="text-[10px] sm:text-[11px] font-medium text-[#64748B]">
                  Indoor Moisture & Airflow
                </span>
              </div>
            </div>

            {/* Status Pill */}
            <span className={`text-[11px] font-extrabold px-2.5 py-0.5 rounded-full border shadow-2xs shrink-0 ${humStatus.badgeClass}`}>
              {humStatus.status}
            </span>
          </div>

          {/* Card Middle: Primary Numerical Value Display */}
          <div className="my-2 flex items-baseline justify-between">
            <div className="flex items-baseline">
              <motion.span
                key={humidity}
                initial={{ opacity: 0.7, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.25 }}
                className="text-3xl sm:text-4xl font-black text-[#0F172A] tracking-tight leading-none"
              >
                {humidity}
              </motion.span>
              <span className="text-lg sm:text-xl font-bold text-[#64748B] ml-1.5">
                %
              </span>
            </div>

            <span className="text-[11px] text-[#64748B] font-medium hidden xs:inline-block">
              Scale: 0% – 100%
            </span>
          </div>

          {/* Card Bottom: Visual Range Indicator Bar */}
          <div className="mt-3 pt-3 border-t border-[#F1F5F9] space-y-1.5">
            <div className="w-full h-2 bg-[#F1F5F9] rounded-full overflow-hidden border border-[#E2E8F0]/70 p-0.5 flex items-center">
              <motion.div
                className="h-full rounded-full transition-all duration-700 ease-out"
                style={{ 
                  backgroundColor: humStatus.indicatorColor,
                  width: `${humPercent}%` 
                }}
                initial={{ width: 0 }}
                animate={{ width: `${humPercent}%` }}
              />
            </div>

            <div className="flex items-center justify-between text-[10px] font-semibold text-[#94A3B8]">
              <span>0%</span>
              <span className="text-[#64748B]">Comfortable ({humScale.COMFORTABLE_RANGE})</span>
              <span>100%</span>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
